# This is a basic workflow to help you get started with Actions

name: gatsby deploy

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v2

      - name: packages install
        run: yarn install

      - name: gatsby build
        run: yarn build
        env:
          # API_KEY 에는 자신이 secret을 생성할 때 설정한 이름으로 넣어야 한다
          GH_API_KEY: ${{ secrets.MY_TOKEN }}

      - name: deploy
        uses: maxheld83/ghpages@v0.2.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # API_KEY 에는 자신이 secret을 생성할 때 설정한 이름으로 넣어야 한다
          GH_PAT: ${{ secrets.MY_TOKEN }}
          BUILD_DIR: 'public/'
